# This workflow runs when receiving an "update-pinmame-native"
# repository_dispatch event from visualpinball/pinmame-dotnet

name: update-pinmame-native
on:
  repository_dispatch:
    types: [ update-pinmame-native ]

jobs:
  update-pinmame-native:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libxml2-utils
      - uses: nuget/setup-nuget@v1
      - uses: actions/checkout@v2
        with:
           path: repo
           fetch-depth: 0
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pinmame-native
          run_id: ${{ github.event.client_payload.run_id }}
          repo: VisualPinball/pinmame-dotnet
      - name: Copy
        run: |
          cd nupkg
          unzip -o PinMame.Native.win-x64.*.nupkg
          cp runtimes/win-x64/native/libpinmame-*.dll ../repo/Plugins/win-x64
          unzip -o PinMame.Native.win-x86.*.nupkg
          cp runtimes/win-x86/native/libpinmame-*.dll ../repo/Plugins/win-x86
          unzip -o PinMame.Native.osx-x64.*.nupkg
          cp runtimes/osx-x64/native/libpinmame.*.dylib ../repo/Plugins/osx-x64
          unzip -o PinMame.Native.linux-x64.*.nupkg
          cp runtimes/linux-x64/native/libpinmame.so.* ../repo/Plugins/linux-x64
      - name: Commit
        run: |
          VERSION=$(xmllint --xpath "//*[local-name()='version']/text()" nupkg/PinMame.Native.win-x64.nuspec)
          cd repo
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(deps): Update PinMame-Native to ${VERSION}."
          git push
