# This workflow runs when receiving an "update-pinmame" 
# repository_dispatch event from visualpinball/pinmame-dotnet

name: update-pinmame
on:
  repository_dispatch:
    types: [ update-pinmame ]

jobs:
  update-pinmame:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libxml2-utils
      - uses: nuget/setup-nuget@v1
      - uses: actions/checkout@v2
        with:
           path: repo
           fetch-depth: 0
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pinmame
          run_id: ${{ github.event.client_payload.run_id }}
          repo: VisualPinball/pinmame-dotnet
      - name: Copy
        run: |
          cd nupkg
          unzip -o PinMame.*.nupkg 
          chmod 644 lib/netstandard2.0/PinMame.dll
          chmod 644 runtimes/osx/lib/netstandard2.0/PinMame.dll
          chmod 644 runtimes/linux/lib/netstandard2.0/PinMame.dll
          cp lib/netstandard2.0/PinMame.dll ../repo/Plugins/win-x64
          cp lib/netstandard2.0/PinMame.dll ../repo/Plugins/win-x86
          cp runtimes/osx/lib/netstandard2.0/PinMame.dll ../repo/Plugins/osx-x64
          cp runtimes/linux/lib/netstandard2.0/PinMame.dll ../repo/Plugins/linux-x64
      - name: Commit
        run: |
          chmod 644 nupkg/PinMame.nuspec
          VERSION=$(xmllint --xpath "//*[local-name()='version']/text()" nupkg/PinMame.nuspec)
          cd repo
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(deps): Update PinMame to ${VERSION}."
          git push
